export const certRows = [
    [
        {imgSrc: '/src/img/certs/aerialGunnery.PNG', altText: 'Aerial Gunnery',},
        { imgSrc: '/src/img/certs/aride.avif', altText: 'Aride' },
        { imgSrc: '/src/img/certs/ASAMDegree.avif', altText: 'ASAM Degree' },
        { imgSrc: '/src/img/certs/bell222.PNG', altText: 'Bell 222' },
        { imgSrc: '/src/img/certs/bell412.PNG', altText: 'Bell 412' },
        { imgSrc: '/src/img/certs/BSBADegree.jpg', altText: 'BSBA Degree' },
    ],
    [
        { imgSrc: '/src/img/certs/ccdg.PNG', altText: 'CCDG' },
        { imgSrc: '/src/img/certs/ccpc.PNG', altText: 'CCPC' },
        { imgSrc: '/src/img/certs/cct.jpg', altText: 'CCT' },
        { imgSrc: '/src/img/certs/fireCard.PNG', altText: 'Fire Card' },
        { imgSrc: '/src/img/certs/dui.PNG', altText: 'DUI' },
        { imgSrc: '/src/img/certs/greyOwel.PNG', altText: 'Grey Owel' },
    ],
    [
        { imgSrc: '/src/img/certs/honorable.jpg', altText: 'Honorable' },
        { imgSrc: '/src/img/certs/htpo.PNG', altText: 'HTPO' },
        { imgSrc: '/src/img/certs/kerryMove.jpg', altText: 'Kerry Move' },
        { imgSrc: '/src/img/certs/lbAward.jpg', altText: 'LB Award' },
        { imgSrc: '/src/img/certs/md530fm.PNG', altText: 'MD 530 FM' },
        { imgSrc: '/src/img/certs/osha10b.PNG', altText: 'OSHA 10B' },
    ],
    [
        { imgSrc: '/src/img/certs/pMech.PNG', altText: 'PMech' },
        { imgSrc: '/src/img/certs/post.jpeg', altText: 'Post' },
        { imgSrc: '/src/img/certs/pt6t.PNG', altText: 'PT6T' },
        { imgSrc: '/src/img/certs/sasMl.PNG', altText: 'SAS ML' },
        { imgSrc: '/src/img/certs/sasVa.PNG', altText: 'SAS VA' },
        { imgSrc: '/src/img/certs/topgun.jpg', altText: 'Top Gun' },
    ],
    [{ imgSrc: '/src/img/certs/webDevFund.png', altText: 'Web Dev Fund' }],
];
